%include "colon.inc"

section .data
colon 'first', fir
db 'explanation one', 0
colon "second", sec
db "explanation two", 0
colon "three",  thr
db "explanation three", 0
colon "four",  four
db "explanation four", 0
colon "five",  five
db "explanation five", 0
colon "five fingers",  six
db "explanation five fingers", 0
colon "five (:-) 	%&7&/*-+3.!4$/;",  seven
db "explanation five (:-) 	%&7&/*-+3.!4$/;", 0